name: Check Commit Messages

on: [push]

jobs:
  commit-message-check:
    runs-on: ubuntu-latest
    steps:
    - name: Check commit message format
      uses: wagoid/commitlint-github-action@v4
      with:
        config: '@commitlint/config-conventional'
        
